### ISSUE TITLE
Verify client can access api

### ISSUE THREAD

**Issue by cjellick** [rancherio/go-machine-service#7]
Currently, if the credentials used to subscribe to events are invalid or the corresponding user doesn't exist, go-machine-service still successfully subscribes, but just receives ping events. It doesn't receive any of the real machine events.

We need to add connection validation logic that verifies the client can access the api. Verifying that something like `GET /machines?limit=1` returns a 200 would probably suffice.

**Comment by deniseschannon** [comment]
Created a new issue in rancherio/rancher. Closing out all issues in go-machine-service repo.

https://github.com/rancherio/rancher/issues/316
