### ISSUE TITLE
Add logic to import a machine from its extractedConfig field

### ISSUE THREAD

**Issue by cjellick** [rancherio/go-machine-service#9]
Add logic to re-import a machine from it's extractedConfig field if that machine doesn't exist on disk.
This will allow to recover from situations where we've lost the go-machine-service's underlying disk (where docker-machine maintains state). This will also allow us to ultimately support mutli-host go-machine-service

Depends on https://github.com/rancherio/go-machine-service/issues/8

**Comment by deniseschannon** [comment]
Moving issues into rancherio/rancher. 

https://github.com/rancherio/rancher/issues/317
